# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0003_auto_20170527_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
