# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0004_touristprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tourist_profile_image),
        ),
        migrations.AlterField(
            model_name='touristtravelphoto',
            name='image',
            field=models.ImageField(upload_to=utils.uploadings.upload_path_handler_tourist_travel_pictures),
        ),
    ]
