# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0005_auto_20170813_1637'),
    ]

    operations = [
    ]
