# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0006_auto_20171012_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tourist_profile_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='touristtravelphoto',
            name='image',
            field=models.ImageField(upload_to=utils.uploadings.upload_path_handler_tourist_travel_pictures, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
