# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_is_featured'),
        ('payments', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
