# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20170625_0046'),
        ('payments', '0004_auto_20170619_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.PaymentStatus'),
        ),
    ]
