# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
