# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
    ]
