# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_dt_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
