# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20170717_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paypal_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
