# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20170818_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
