# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20170818_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardType',
            new_name='PaymentMethodType',
        ),
    ]
