# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20170818_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
