# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20170818_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
