# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_paymentmethod_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cvv',
        ),
    ]
