# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20170831_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
