# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20170831_0030'),
        ('payments', '0017_remove_paymentmethod_cvv'),
    ]

    operations = [
    ]
