# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymentmethod_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='nonce',
        ),
    ]
