# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_paymentmethod_nonce'),
        ('payments', '0018_merge_20170903_0117'),
    ]

    operations = [
    ]
