# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20180506_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
