# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_paymentmethod_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='errors_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
