# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideprofile',
            old_name='bio',
            new_name='overview',
        ),
    ]
