# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_guideprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='slug',
            field=models.SlugField(default=utils.general.random_string_creating, max_length=200, unique=True),
        ),
    ]
