# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170422_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
