# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_guideprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='header_image',
            field=models.ImageField(blank=True, default='300x300.png', null=True, upload_to='guides/header_images'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='optional_image',
            field=models.ImageField(blank=True, default='300x300.png', null=True, upload_to='guides/optional_images'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='300x300.png', null=True, upload_to='guides/profile_images'),
        ),
    ]
