# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170501_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
    ]
