# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_interest_userinterest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceGuide',
            new_name='GuideService',
        ),
        migrations.AddField(
            model_name='service',
            name='html_field_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
