# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_auto_20170506_1314'),
        ('users', '0017_auto_20170504_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guideservice',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='guideservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuideProfile',
        ),
        migrations.DeleteModel(
            name='GuideService',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
