# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_paymentcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
