# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_auto_20170619_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('twitter', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('google', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('address_full', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
