# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170721_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralProfileScan',
            new_name='DocumentScan',
        ),
    ]
