# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20170721_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='general_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GeneralProfile'),
        ),
    ]
