# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_documentscan_general_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
