# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_generalprofile_phone_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='phone_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
