# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0034_generalprofile_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSendingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_long', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('sms_code', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('tries_nmb', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
