# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_smssendinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='phone_code',
        ),
    ]
