# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_generalprofile_phone_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalprofile',
            old_name='phone_is_verified',
            new_name='phone_is_validated',
        ),
    ]
