# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20170726_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smssendinghistory',
            old_name='phone_number_long',
            new_name='phone',
        ),
    ]
