# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20170726_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
