# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_generalprofile_is_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='business_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
