# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20170731_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='phone_pending',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
