# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0025_auto_20171005_0303'),
        ('users', '0041_generalprofile_phone_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='general_profile',
        ),
        migrations.AddField(
            model_name='documentscan',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
    ]
