# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20171005_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='status',
        ),
        migrations.DeleteModel(
            name='DocumentScan',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='ScanStatus',
        ),
    ]
