# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20171005_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_previously_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
