# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-14 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_generalprofile_is_verified'),
        ('users', '0046_auto_20171012_0529'),
    ]

    operations = [
    ]
