# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merge_20171014_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='is_verified',
        ),
    ]
