# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_generalprofile_webcam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='webcam_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_webcam_image),
        ),
    ]
