# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_generalprofile_webcam_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='is_previously_logged_in',
        ),
    ]
