# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_generalprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
