# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20171024_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='is_trusted',
        ),
        migrations.RemoveField(
            model_name='generalprofile',
            name='is_verified',
        ),
    ]
