# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20171024_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
