# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_generalprofile_webcam_image'),
        ('users', '0055_auto_20171024_2244'),
    ]

    operations = [
    ]
