# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_merge_20171027_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='registration_building_nmb',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_flat_nmb',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_postcode',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_state',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='registration_street',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
