# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20171217_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='generalprofile',
            name='address_full',
        ),
        migrations.RemoveField(
            model_name='generalprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='generalprofile',
            name='country',
        ),
    ]
