# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20171217_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='registration_country_ISO_3_digits',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
