# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20171217_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
