# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20180104_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
