# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-04 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20180104_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='generalprofile',
            name='date_of_birth',
        ),
    ]
