# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_generalprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='instagram',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
