# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20180104_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
