# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_generalprofile_instagram'),
        ('users', '0066_auto_20180106_0926'),
    ]

    operations = [
    ]
