# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_generalprofile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='uuid',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
