# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-12 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_generalprofile_uuid'),
        ('users', '0067_merge_20180107_2333'),
    ]

    operations = [
    ]
