# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_merge_20180212_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='total_tourists_referred',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='tourist_referral',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
