# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20180411_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='tourist_referral',
            field=models.CharField(blank=True, default=utils.general.uuid_creating, max_length=8, null=True),
        ),
    ]
