# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20180411_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='tourist_referral',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
