# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20180411_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='tourist_referral',
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='referral_code',
            field=models.CharField(default='c91c4ab6787f47f0b68b15d1e3b42aff', max_length=64),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='total_guides_referred',
            field=models.IntegerField(default=0),
        ),
    ]
