# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20180413_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='referral_code',
        ),
    ]
