# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_remove_generalprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
