# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_generalprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_fee_free',
            field=models.BooleanField(default=False),
        ),
    ]
