# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-29 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0077_generalprofile_is_fee_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
