# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_generalprofile_referred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalprofile',
            old_name='total_guides_referred',
            new_name='guides_referred_nmb',
        ),
        migrations.RenameField(
            model_name='generalprofile',
            old_name='total_tourists_referred',
            new_name='guides_verified_referred_nmb',
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='tourists_referred_nmb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='tourists_with_purchases_referred_nmb',
            field=models.IntegerField(default=0),
        ),
    ]
