# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20180728_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='device_id',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
    ]
