# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_generalprofile_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='device_id',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
    ]
