# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20180904_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
