# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20180928_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='is_express_signup_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='is_express_signup_initial',
            field=models.BooleanField(default=False),
        ),
    ]
