# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20181230_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssendinghistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='smssendinghistory',
            name='type',
        ),
        migrations.DeleteModel(
            name='SMSType',
        ),
    ]
