# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20181230_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
