# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_generalprofile_sms_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='sms_notifications',
            field=models.NullBooleanField(default=None),
        ),
    ]
