# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_partner'),
        ('guides', '0018_guideprofile_uuid'),
        ('guides_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItemGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'booked'), ('available', 'available'), ('unavailable', 'unavailable')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Calendar',
            new_name='CalendarItem',
        ),
        migrations.AlterModelOptions(
            name='calendaritem',
            options={'verbose_name': 'Calendar Item', 'verbose_name_plural': 'Calendar Items'},
        ),
        migrations.AddField(
            model_name='calendaritemguide',
            name='calendar_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides_calendar.CalendarItem'),
        ),
        migrations.AddField(
            model_name='calendaritemguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
        migrations.AddField(
            model_name='calendaritemguide',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
