# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides_calendar', '0002_auto_20170930_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendaritemguide',
            options={'verbose_name': 'Guide Calendar Item', 'verbose_name_plural': 'Guide Calendar Items'},
        ),
    ]
