# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0018_guideprofile_uuid'),
        ('guides_calendar', '0003_auto_20170930_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calendar Item Status',
                'verbose_name_plural': 'Calendar Item Statuses',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile')),
            ],
            options={
                'verbose_name': 'Guide Calendar Item',
                'verbose_name_plural': 'Guide Calendar Items',
            },
        ),
        migrations.RemoveField(
            model_name='calendaritemguide',
            name='status',
        ),
    ]
