# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides_calendar', '0004_auto_20171001_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritemguide',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides_calendar.CalendarItemStatus'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides_calendar.CalendarItemStatus'),
        ),
    ]
