# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides_calendar', '0005_auto_20171001_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleTemplate',
            new_name='ScheduleTemplateItem',
        ),
        migrations.AlterModelOptions(
            name='scheduletemplateitem',
            options={'verbose_name': 'Schedule Template Item', 'verbose_name_plural': 'Schedule Template Items'},
        ),
    ]
