# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides_calendar', '0006_auto_20171001_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritemstatus',
            name='available',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='calendaritemstatus',
            name='booked',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='calendaritemstatus',
            name='unavailable',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
