# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0002_remove_pagecontent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
