# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0004_contactusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmessage',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
