# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0006_auto_20171012_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_homepage)),
                ('image_large', models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_homepage_large)),
                ('image_medium', models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_homepage_medium)),
                ('image_small', models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_homepage_small)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
