# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0007_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTheNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('url', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
