# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0008_inthenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presskit', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
