# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guideprofile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
