# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guideprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='rating',
        ),
    ]
