# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_remove_guideprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
