# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_guideprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
