# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_auto_20170506_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideservice',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
