# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20170528_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideservice',
            old_name='rate',
            new_name='price',
        ),
    ]
