# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_is_featured'),
        ('guides', '0009_auto_20170529_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='currency',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Currency'),
        ),
    ]
