# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0011_remove_guideprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
