# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_guideprofile_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='is_company',
        ),
    ]
