# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_remove_guideprofile_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='header_image',
            field=models.ImageField(blank=True, default='guides/header_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_guide_header_images),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='optional_image',
            field=models.ImageField(blank=True, default='guides/optional_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_guide_optional_image),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='guides/profile_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image),
        ),
    ]
