# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0014_auto_20170813_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='min_hours',
            field=models.IntegerField(default=1),
        ),
    ]
