# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0015_guideprofile_min_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='is_active',
        ),
    ]
