# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0017_guideprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='uuid',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
