# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0019_guideprofile_webcam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
