# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0020_guideprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='onfido_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
