# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0022_auto_20171005_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuideIdentificationChecking',
            new_name='GuideIdentityValidation',
        ),
        migrations.RenameModel(
            old_name='GuideIdentificationCheckingReport',
            new_name='GuideIdentityValidationReport',
        ),
        migrations.RenameModel(
            old_name='CheckingReportType',
            new_name='ValidationReportResult',
        ),
        migrations.RenameModel(
            old_name='CheckingReportStatus',
            new_name='ValidationReportStatus',
        ),
        migrations.RenameModel(
            old_name='CheckingReportResult',
            new_name='ValidationReportType',
        ),
        migrations.RenameField(
            model_name='guideprofile',
            old_name='is_approved',
            new_name='is_validated',
        ),
    ]
