# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0023_auto_20171005_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuideIdentityValidation',
            new_name='GuideIdentityVerification',
        ),
        migrations.RenameModel(
            old_name='GuideIdentityValidationReport',
            new_name='GuideIdentityVerificationReport',
        ),
        migrations.RenameModel(
            old_name='ValidationReportResult',
            new_name='VerificationReportResult',
        ),
        migrations.RenameModel(
            old_name='ValidationReportStatus',
            new_name='VerificationReportStatus',
        ),
        migrations.RenameModel(
            old_name='ValidationReportType',
            new_name='VerificationReportType',
        ),
        migrations.RenameField(
            model_name='guideprofile',
            old_name='is_validated',
            new_name='is_verified',
        ),
    ]
