# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0024_auto_20171005_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideidentityverificationreport',
            name='result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.VerificationReportResult'),
        ),
        migrations.AlterField(
            model_name='guideidentityverificationreport',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.VerificationReportType'),
        ),
    ]
