# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0027_auto_20171005_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuideIdentityVerification',
            new_name='IdentityVerification',
        ),
        migrations.RenameModel(
            old_name='GuideIdentityVerificationReport',
            new_name='IdentityVerificationReport',
        ),
    ]
