# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0028_auto_20171005_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='identityverificationreport',
            name='identification_checking',
        ),
        migrations.RemoveField(
            model_name='identityverificationreport',
            name='result',
        ),
        migrations.RemoveField(
            model_name='identityverificationreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='identityverificationreport',
            name='type',
        ),
        migrations.DeleteModel(
            name='DocumentScan',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='IdentityVerification',
        ),
        migrations.DeleteModel(
            name='IdentityVerificationReport',
        ),
        migrations.DeleteModel(
            name='ScanStatus',
        ),
        migrations.DeleteModel(
            name='VerificationReportResult',
        ),
        migrations.DeleteModel(
            name='VerificationReportStatus',
        ),
        migrations.DeleteModel(
            name='VerificationReportType',
        ),
    ]
