# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0031_auto_20171012_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='registration_building',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_postcode',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_street',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
