# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0032_auto_20171217_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideprofile',
            old_name='registration_building',
            new_name='registration_building_nmb',
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_flat_nmb',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='registration_state',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
