# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0033_auto_20171217_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_building_nmb',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_city',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_country',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_flat_nmb',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_postcode',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_state',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='registration_street',
        ),
    ]
