# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0034_auto_20171217_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
