# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0035_guideprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='last_name',
        ),
    ]
