# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0036_remove_guideprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=utils.uploadings.upload_path_handler_guide_image)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='guideanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Question'),
        ),
    ]
