# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0038_auto_20180107_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideanswer',
            name='order_priority',
            field=models.IntegerField(default=0),
        ),
    ]
