# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0039_guideanswer_order_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploadings.upload_path_handler_guide_image),
        ),
    ]
