# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0040_auto_20180107_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideanswer',
            old_name='answer',
            new_name='text',
        ),
    ]
