# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0041_auto_20180107_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_default_guide',
            field=models.BooleanField(default=True),
        ),
    ]
