# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-08 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0042_guideprofile_is_default_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='is_default_guide',
        ),
    ]
