# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    pass

    #AT: commented out 27.07.2018 due to issue with migrations merging. The same operations is in the migration guides 0045

    dependencies = [
        ('guides', '0045_guideprofile_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_default_guide',
            field=models.BooleanField(default=False),
        ),
    ]
