# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0047_auto_20180307_0756'),
        ('guides', '0044_guideprofile_is_default_guide'),
        ('guides', '0042_guideprofile_is_default_guide'),
    ]

    operations = [
    ]
