# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0045_guideprofile_license_image'),
        ('guides', '0048_merge_20180309_1254'),
    ]

    operations = [
    ]
