# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-10 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0048_merge_20180309_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='license_image',
            field=models.ImageField(blank=True, default='guides/optional_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_guide_license),
        ),
    ]
