# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0049_merge_20180319_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='additional_person_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
