# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0050_guideprofile_additional_person_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='guides/profile_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
