# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0051_auto_20180611_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_use_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
