# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0053_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideanswer',
            name='image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_answer_image_large),
        ),
        migrations.AddField(
            model_name='guideanswer',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_answer_image_medium),
        ),
        migrations.AddField(
            model_name='guideanswer',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_answer_image_small),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image_large),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image_medium),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image_small),
        ),
        migrations.AlterField(
            model_name='guideanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_answer_image),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='header_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_header_images),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='optional_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_optional_image),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_guide_profile_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
