# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0054_auto_20180722_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
