# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.CharField(max_length=48)),
                ('website', models.URLField()),
            ],
        ),
    ]
