# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='uuid',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
