# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170918_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
