# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20170918_0004'),
    ]

    operations = [
    ]
