# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0004_auto_20171012_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='partner',
            name='api_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='billing_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='requesting_person',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tax_id',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
