# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20171029_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
