# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_remove_partner_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
