# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20171029_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='reason_requesting',
            field=models.TextField(null=True),
        ),
    ]
