# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-02 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
    ]
