# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0046_auto_20180716_1952'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='uuid',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
