# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20180520_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uuid',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
