# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-02 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
