# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponuser',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
