# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
