# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_hourly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
