# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20170309_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hours',
            field=models.IntegerField(default=1),
        ),
    ]
