# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
