# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_review_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='user',
            new_name='guide',
        ),
    ]
