# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
    ]
