# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20170312_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='overview',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
