# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
    ]
