# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, default=utils.general.random_string_creating, max_length=200, null=True, unique=True),
        ),
    ]
