# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_auto_20170312_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
    ]
