# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_auto_20170319_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
