# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_tour_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='/tours/images/default_tour_image.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_tour),
        ),
    ]
