# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_auto_20170430_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_from_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_from_tourist',
            field=models.BooleanField(default=False),
        ),
    ]
