# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_hours_nmb'),
        ('tours', '0024_auto_20170502_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
