# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_auto_20170502_2311'),
        ('guides', '0001_initial'), #added manually for solving an issue with migrations
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
    ]
