# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_auto_20170506_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
