# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_tour_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='/tours/images/default_tour_image.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_tour_small),
        ),
    ]
