# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_auto_20170815_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_medium),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_small),
        ),
    ]
