# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0031_auto_20170815_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_medium',
            field=models.ImageField(blank=True, default='/tours/images/default_tour_image_medium.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_tour_medium),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_small',
            field=models.ImageField(blank=True, default='/tours/images/default_tour_image_small.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_tour_small),
        ),
    ]
