# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0033_auto_20171012_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='excluded',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
