# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0034_auto_20180404_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourActivityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.IntegerField(default=1)),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('image_large', models.ImageField(upload_to=utils.uploadings.upload_path_handler_tour_images)),
                ('image_medium', models.ImageField(upload_to=utils.uploadings.upload_path_handler_tour_images)),
                ('image_small', models.ImageField(upload_to=utils.uploadings.upload_path_handler_tour_images)),
            ],
        ),
        migrations.CreateModel(
            name='TourExcludedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourIncludedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
    ]
