# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0035_touractivitydescription_tourexcludeditem_tourincludeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='touractivitydescription',
            name='tour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
