# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0036_touractivitydescription_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touractivitydescription',
            name='image_large',
            field=models.ImageField(blank=True, default='guides/header_images/300x300.png', null=True, upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
    ]
