# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0037_auto_20180611_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='touractivitydescription',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
        migrations.AlterField(
            model_name='touractivitydescription',
            name='image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
        migrations.AlterField(
            model_name='touractivitydescription',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
        migrations.AlterField(
            model_name='touractivitydescription',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_images),
        ),
    ]
