# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0041_tourprogramitem_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_final', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('places_total', models.IntegerField(default=0)),
                ('places_booked', models.IntegerField(default=0)),
                ('places_available', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
    ]
