# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0042_scheduledtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
