# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0043_scheduledtour_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtour',
            old_name='places_available',
            new_name='seats_available',
        ),
        migrations.RenameField(
            model_name='scheduledtour',
            old_name='places_booked',
            new_name='seats_booked',
        ),
        migrations.RenameField(
            model_name='scheduledtour',
            old_name='places_total',
            new_name='seats_total',
        ),
    ]
