# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0044_auto_20180615_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='overview_short',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
