# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0045_tour_overview_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourexcludeditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
