# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0046_tourexcludeditem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('time_start', models.TimeField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seats_total', models.IntegerField(default=0)),
                ('is_general_template', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            options={
                'verbose_name': 'Schedule Template Item',
                'verbose_name_plural': 'Schedule Template Items',
            },
        ),
        migrations.AddField(
            model_name='scheduledtour',
            name='time_start',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tourprogramitem',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tourprogramitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
