# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0047_auto_20180714_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplateitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
