# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0049_remove_scheduletemplateitem_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplateitem',
            name='day',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
