# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0050_scheduletemplateitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplateitem',
            name='day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=None, max_length=1, null=True),
        ),
    ]
