# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0051_auto_20180715_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='tourprogramitem',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
