# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0052_auto_20180716_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtour',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
