# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0053_scheduledtour_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='additional_person_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_persons_nmb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='persons_nmb_for_min_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'Scheduled'), (2, 'Private')], default=1, max_length=12, null=True),
        ),
    ]
