# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0054_auto_20180717_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
    ]
