# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0056_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Scheduled - this tour must take place with any number of participants on schedule.'), ('2', 'Private - this tour must take place in the custom date and time after your negotiation with a tourist and approve it.')], default='2', max_length=12, null=True),
        ),
    ]
