# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0058_tour_price_after_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='price_after_discount',
            new_name='price_final',
        ),
    ]
