# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0059_auto_20180720_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_large',
            field=models.ImageField(blank=True, default='/tours/images/default_tour_image_large.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_tour_large),
        ),
    ]
