# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0061_auto_20180723_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_large),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_medium),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_tour_small),
        ),
    ]
