# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0063_auto_20180723_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='max_persons_nmb',
            field=models.IntegerField(default=10),
        ),
    ]
