# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0064_auto_20180723_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='persons_nmb_for_min_price',
            field=models.IntegerField(default=1),
        ),
    ]
