# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0065_auto_20190104_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='order_priority',
            field=models.IntegerField(default=0),
        ),
    ]
