# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0068_curatedtours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtours',
            name='destination',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
