# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0070_auto_20200218_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtours',
            name='destination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Country'),
        ),
    ]
