# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0071_auto_20200218_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtours',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=1000, null=True), blank=True, default=None, size=None),
        ),
    ]
