# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20180722_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotracker',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geotracker',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
