# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0046_auto_20180709_0335'),
        ('mobile', '0002_geochat_geochatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('in_progress', models.BooleanField(default=False)),
                ('cost', models.FloatField()),
                ('time_remaining', models.IntegerField()),
                ('time_flag', models.CharField(max_length=64)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='geotracker',
            name='trip_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
