# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 06:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20180710_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotracker',
            name='geo_point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
