# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order_duration_seconds'),
        ('mobile', '0004_auto_20180723_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotrip',
            name='order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
