# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20180710_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geotracker',
            name='geo_point',
        ),
    ]
