# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_geotrip_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotrip',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotrip_guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geotrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotrip_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
