# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20180825_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('comments', models.TextField()),
            ],
        ),
    ]
