# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 07:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_remove_geotracker_geo_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotracker',
            name='geo_point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), geography=True, srid=4326),
        ),
    ]
