# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170712_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_blog),
        ),
    ]
