# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogposttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='posts_nmb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='posts_nmb',
            field=models.IntegerField(default=0),
        ),
    ]
