# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170713_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='defaults/blog_post_default.jpg', null=True, upload_to=utils.uploadings.upload_path_handler_blog),
        ),
    ]
