# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170713_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='posts_nmb',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='posts_nmb',
        ),
    ]
