# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171012_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_image_optimized',
            field=models.BooleanField(default=False),
        ),
    ]
