# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_is_image_optimized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, default=utils.general.random_string_creating, null=True),
        ),
    ]
