# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_country_position_index'),
        ('blog', '0012_auto_20180208_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Country'),
        ),
    ]
