# -*- coding: utf-8 -*-

"""
Django settings for tourzan project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _
import datetime


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd370859b5!ee4ea_9c5e%d11m7qin7lr*c&6#8e@9cf151b3ec'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
ILLEGAL_COUNTRIES = ['Democratic Republic of the Congo', 'Cuba', 'Iran', 'Iraq',
                     "Côte d'Ivoire", 'North Korea', 'Lebanon', 'Liberia', 'Libya',
                     'Myanmar (Burma)', 'Somalia', 'Sudan', 'Syria', 'Venezuela',
                     'Yemen', 'Zaire', 'Zimbabwe']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'locations',
    'tours',
    'orders',
    'chats',
    'users',

    'guides',
    'tourists',
    'website_management',
    'emails',
    'payments',
    'blog',
    'partners',
    'guides_calendar',
    'user_verification',
    'utils',
    'coupons',
    'mobile',
    'notifications',

    #external packages
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'live_chat',

    'channels',
    'crequest',
    'django_summernote',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework.schemas',
    'rest_framework.documentation',
    'rest_auth',
    'storages',
    'axes',
    'phonenumber_field',
    'drip',
    'django_social_share',

    # 'corsheaders',
    'django_extensions',
    'django_user_agents',
    'crispy_forms',
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    #middleware for localization
    # 'users.middleware.ForceDefaultLanguageMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_user_agents.middleware.UserAgentMiddleware',
    'crequest.middleware.CrequestMiddleware',
    'users.middleware.TrackingActiveUserMiddleware',
    'users.middleware.ReferralCodesGettingMiddleware',

    # 'django.middleware.cache.FetchFromCacheMiddleware',

]

# CORS_ORIGIN_WHITELIST = (
#     'google.com',
#     'https://widget.paymentrails.com',
#     'widget.paymentrails.com',
#     'paymentrails.com'
# )

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'tourzan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static/templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n', # for localization
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.site'
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'NOTSET',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'NOTSET',
        },
        'django.request': {
            'handlers': ['console'],
            'propagate': False,
            'level': 'ERROR'
        }
    }
}

WSGI_APPLICATION = 'tourzan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'uuid-malloc01',
        'TIMEOUT': 61000,
    }
}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 61000
CACHE_MIDDLEWARE_KEY_PREFIX = ''

SITE_ID = 1

"""
for allauth
"""
LOGIN_REDIRECT_URL = "/after_login_router/"
# LOGIN_URL = '/'


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#Django Restful API settings
REST_FRAMEWORK = {
    #commented out for testin purpose

    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=3000),
}

LOGOUT_ON_PASSWORD_CHANGE = False
REST_SESSION_LOGIN = False
REST_USE_JWT = True
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'users.api.serializers.UserDetailsSerializerCustom',
    'PASSWORD_RESET_SERIALIZER': 'users.api.serializers.PasswordResetSerializerCustom',
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'users.api.serializers.PasswordResetConfirmSerializerCustom',
}


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('de', _('German')),
    ('pt', _('Portuguese')),
    ('ja', _('Japanese')),
    ('ru', _('Russian')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#Mail settings
EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = 'Django_testing'
# EMAIL_HOST_PASSWORD = 'Testing12#$'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DRIP_FROM_EMAIL = 'contactus@tourzan.com'
FROM_EMAIL = "noreply@tourzan.com"

GOOGLE_RECAPTCHA_SITE_KEY = "6LdGbGgUAAAAANpsXrF3-JikS3mDRlwH1sVuBok3"
# GOOGLE_RECAPTCHA_SECRET_KEY = "6LcH3h4TAAAAABBUj4ci88yDIaM_A1A2YYt4IeTr"
GOOGLE_RECAPTCHA_SECRET_KEY = "6LdGbGgUAAAAALDT1U-vUeu5HygXxFiuYb1RFN28"

TWILIO_ACCOUNT_SID = "AC9c724976ac8617d597ddf08ea76e522b"
TWILIO_AUTH_TOKEN = "b39c735874f5e41f2bf9e64b7960617b"
TWILIO_FROM_PHONE = "888-856-0706"

USER_SMS_NMB_LIMIT = 3
PHONE_SMS_NMB_LIMIT = 3
DAILY_SMS_NMB_LIMIT = 10000 #to limit expenses in case of unexpected issues

AXES_COOLOFF_TIME = 3

# Number of seconds of inactivity before a user is marked offline
USER_ONLINE_TIMEOUT = 5*60

# Number of seconds that we will keep track of inactive users for before
# their last seen is removed from the cache
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static", "static_prod")

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, "static", "static_dev"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")

ON_PRODUCTION = False #in prod_settings it is ON_PRODUCTION=True. This is used for braintree and possibly some other settings
GOOGLE_MAPS_KEY = os.environ.get("GOOGLE_MAPS_KEY", "AIzaSyB4M-SKd4ihX9l4W5Dz4ZUWOqHG3seEGYw")
FCM_API_KEY = 'AAAAYMNPZ9o:APA91bHTblh5t3D-dEJpYCTDSvmx3Mhn9_EPChOghBlEn9dQzroucP8EN18TgExvyzfoIeA_HFn_OcUR_a6v-ssgEbO0Nmul8YuttFFpHWOgFMuG9hwA4aoR9Mrg8qLEKKh2vu_TuNIaU_hB09DIvN-yDIJ-JBui5Q'


# Channels
ASGI_APPLICATION = 'tourzan.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

try:
    from .allauth_settings import *
except:
    pass


try:
    #delete '_2' on AWS
    from .prod_settings_2 import *
except:
    pass


try:
    #delete '_2' on Testing server of AWS
    from .test_settings_2 import *
except:
    pass


try:
    #local settings, specific for your machine
    from .local_settings import *
except Exception as e:
    print(e)
    pass

# #removing this 2 caching middlewares to allow to see immediately changes, made to html pages while coding
# MIDDLEWARE.remove("django.middleware.cache.UpdateCacheMiddleware")\
#     .remove("django.middleware.cache.FetchFromCacheMiddleware")

