# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
