# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_uuid'),
        ('chats', '0008_auto_20171012_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
