# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20180826_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
