# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=64, null=True)),
                ('checks_url', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='identityverification',
            old_name='onfido_id',
            new_name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='checks_url',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='applicant_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
