# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_auto_20171006_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverificationreport',
            name='identification_checking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifications.IdentityVerificationCheck'),
        ),
    ]
