# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_auto_20171006_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentityVerification',
            new_name='IdentityVerificationApplicant',
        ),
    ]
