# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0004_auto_20171006_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationcheck',
            name='applicant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verifications.IdentityVerificationApplicant'),
        ),
    ]
