# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0005_identityverificationcheck_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationreport',
            name='report_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
