# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0006_identityverificationreport_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityverificationcheck',
            old_name='checks_url',
            new_name='check_url',
        ),
    ]
