# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0007_auto_20171007_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='onfido_href',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='documentscan',
            name='onfido_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
