# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0008_auto_20171007_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='onfido_href',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='onfido_id',
        ),
    ]
