# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0010_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='error_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='is_successfully_processed',
            field=models.BooleanField(default=False),
        ),
    ]
