# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0011_auto_20171025_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='general_profile',
        ),
    ]
