# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0010_auto_20171012_0529'),
        ('verifications', '0011_auto_20171025_1340'),
    ]

    operations = [
    ]
