# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_merge_20171027_0151'),
        ('verifications', '0010_auto_20171012_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScanNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_user_scanned_docs)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verifications.DocumentType')),
                ('general_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GeneralProfile')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='verifications.ScanStatus')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('is_successfully_processed', models.BooleanField(default=False)),
                ('error_text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='documentscan',
        #     name='document_type',
        # ),
        # migrations.RemoveField(
        #     model_name='documentscan',
        #     name='general_profile',
        # ),
        # migrations.RemoveField(
        #     model_name='documentscan',
        #     name='status',
        # ),
        # migrations.DeleteModel(
        #     name='DocumentScan',
        # ),
    ]
