# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0012_merge_20171026_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentscan',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='general_profile',
        ),
        migrations.RemoveField(
            model_name='documentscan',
            name='status',
        ),
        migrations.DeleteModel(
            name='DocumentScan',
        ),
    ]
