# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0012_merge_20171026_2221'),
        ('verifications', '0013_documentscan_general_profile'),
    ]

    operations = [
    ]
