# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0013_auto_20171027_1452'),
        ('verifications', '0012_auto_20171025_1340'),
    ]

    operations = [
    ]
