# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_generalprofile_is_previously_logged_in'),
        ('verifications', '0013_remove_documentscan_general_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='general_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GeneralProfile'),
        ),
    ]
