# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0014_merge_20171027_0201'),
        ('verifications', '0015_documentscan'),
    ]

    operations = [
    ]
