# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0015_merge_20171027_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='test_field',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
