# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0017_documentscan'),
        ('verifications', '0016_merge_20171027_0216'),
    ]

    operations = [
    ]
