# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='locations/cities'),
        ),
    ]
