# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
