# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_city),
        ),
    ]
