# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20170813_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_gmaps_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_original_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
