# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20170905_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_gmaps_id',
            new_name='gmaps_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_original_name',
            new_name='original_name',
        ),
    ]
