# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20170905_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='gmaps_id',
            new_name='place_id',
        ),
    ]
