# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20170905_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='full_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
