# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_city_full_location'),
    ]

    operations = [
    ]
