# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_city_image_small'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='image_small',
            new_name='image_medium',
        ),
    ]
