# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import utils.general
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20180523_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_city_large),
        ),
        migrations.AddField(
            model_name='city',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_city_small),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_country),
        ),
        migrations.AddField(
            model_name='country',
            name='image_large',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_country_large),
        ),
        migrations.AddField(
            model_name='country',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_country_medium),
        ),
        migrations.AddField(
            model_name='country',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_country_small),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default=utils.general.random_string_creating, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.upload_path_handler_city_medium),
        ),
    ]
