# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20180728_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='position_index',
            field=models.IntegerField(default=0),
        ),
    ]
