# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='session_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='search_word',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
