# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20181117_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='location',
        ),
    ]
