# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_remove_searchlog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Country'),
        ),
    ]
