# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0021_auto_20181117_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLocationTourRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=3000, null=True)),
                ('tour_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[(10, 'New'), (20, 'Processing'), (30, 'Processing'), (40, 'Cancelled')], default=10, max_length=20)),
                ('tourzan_notes', models.TextField(blank=True, default=None, max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
