# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_auto_20181117_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlocationtourrequest',
            name='location_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newlocationtourrequest',
            name='location_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
