# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0024_auto_20181117_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlocationtourrequest',
            name='number_persons',
            field=models.IntegerField(default=1),
        ),
    ]
