# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0025_newlocationtourrequest_number_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlocationtourrequest',
            name='status',
            field=models.CharField(choices=[(10, 'New'), (20, 'Processing'), (30, 'Processed'), (40, 'Cancelled')], default=10, max_length=20),
        ),
    ]
