# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_auto_20181118_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlocationtourrequest',
            name='status',
            field=models.CharField(choices=[('10', 'New'), ('20', 'Processing'), ('30', 'Processed'), ('40', 'Cancelled')], default='10', max_length=20),
        ),
    ]
