# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_auto_20181118_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
