# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hours_nmb',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
