# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_booked_for',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
