# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_date_booked_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hours_nmb',
        ),
    ]
