# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_hours_nmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours_nmb',
            field=models.IntegerField(default=0),
        ),
    ]
