# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170506_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_guide',
            new_name='is_from_guide',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_tourist',
            new_name='is_from_tourist',
        ),
    ]
