# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_tour_is_deleted'),
        ('orders', '0011_auto_20170523_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
