# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='guide_feedback',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='guide_feedback_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='guide_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_from_guide',
            new_name='is_guide_feedback',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_from_tourist',
            new_name='is_toursit_feedback',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_active',
        ),
        migrations.AddField(
            model_name='review',
            name='toursit_feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='toursit_feedback_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='toursit_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
