# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20170528_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
    ]
