# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20170528_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tourist_review_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='tourist_review_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
