# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20170528_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_toursit_feedback',
            new_name='is_tourist_feedback',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='toursit_feedback',
            new_name='tourist_feedback',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='toursit_feedback_name',
            new_name='tourist_feedback_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='toursit_rating',
            new_name='tourist_rating',
        ),
    ]
