# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20170528_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='guide_feedback',
            new_name='guide_feedback_text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tourist_feedback',
            new_name='tourist_feedback_text',
        ),
    ]
