# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20170624_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'not_paid'), ('paid', 'paid'), ('partially_paid', 'partially_paid')], default='not_paid', max_length=32),
        ),
    ]
