# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20170625_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_paid',
        ),
    ]
