# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20170625_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
