# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('orders', '0028_auto_20170719_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
    ]
