# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20171012_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_person_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='number_persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='price_additional_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
