# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20180403_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_additional_person',
        ),
        migrations.AddField(
            model_name='order',
            name='price_per_additional_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
