# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0053_scheduledtour_uuid'),
        ('coupons', '0002_auto_20180717_0742'),
        ('orders', '0032_auto_20180403_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='guide_compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='guide_fees_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='is_discount_on_tourzan_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='tour_scheduled',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.ScheduledTour'),
        ),
        migrations.AddField(
            model_name='order',
            name='tourist_fees_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_toured',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
