# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20180520_1805'),
        ('orders', '0032_auto_20180403_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_discount_on_tourzan_side',
            field=models.BooleanField(default=False),
        ),
    ]
