# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20180520_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
