# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_total_price_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guide_compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='guide_fees_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='tourist_fees_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
