# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0044_auto_20180615_2002'),
        ('orders', '0035_auto_20180521_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tour_scheduled',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.ScheduledTour'),
        ),
    ]
