# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_tour_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_toured',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
