# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved_by_guide',
            field=models.BooleanField(default=False),
        ),
    ]
