# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_is_approved_by_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_additional_persons',
            field=models.IntegerField(default=0),
        ),
    ]
