# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_number_additional_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guide_payout_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
