# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_order_guide_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
