# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderStatus')),
            ],
        ),
    ]
