# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0055_auto_20180804_0202'),
        ('orders', '0044_otherreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherreviews',
            name='guide',
        ),
        migrations.AddField(
            model_name='otherreviews',
            name='guide',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='guides.GuideProfile'),
        ),
    ]
