# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0055_auto_20180804_0202'),
        ('orders', '0045_auto_20180928_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherreviews',
            name='guide',
        ),
        migrations.AddField(
            model_name='otherreviews',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.GuideProfile'),
        ),
    ]
