# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20180928_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherreviews',
            name='tourist_name',
        ),
        migrations.AddField(
            model_name='otherreviews',
            name='tourist_first_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherreviews',
            name='tourist_last_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
