# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_auto_20180928_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
