# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=240)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
