# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
