# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='call_to_action',
            field=models.CharField(default='', max_length=32),
        ),
    ]
