# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentScanNew',
            new_name='DocumentScan',
        ),
    ]
