# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0002_auto_20171027_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
